### ISSUE TITLE
Отсутсвуют стрелки how it works как на макете

### ISSUE THREAD

**Issue by Sharabaddin** [akhmaiev/akhmaiev.github.io#17]

**Comment by akhmaiev** [comment]
это кстати проблема появилась когда я захостил. Если локально открывать сайт то без проблем

**Comment by akhmaiev** [comment]
попробую что то  с этим сделать

**Comment by Sharabaddin** [comment]
Я уже поборол эту бажину. Просьба повнимательней и поосновательней разобраться.

**Comment by akhmaiev** [comment]
решение не найдено

**Comment by Sharabaddin** [comment]
Обрати внимания на регистрозависимость. В виндовсе файлы не ригистрозависимы в линуксе и маке регистрзависимы.
